name: dev-deploy CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  dev-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
    # - name: Create env file
    #   run: | # cp sample.env.yml env.yml
    #     cat > env.yml << EOF
    #     ${{ secrets.ENV }}
    #     EOF
    - name: Install NPM dependencies
      run: npm install
    - name: Deploy Lambda functions
      run: NODE_ENV=dev sls deploy -s dev
